
import {
  PRAYAGRAJ_CHEAPEST_ROUTES,
  AYODHYA_CHEAPEST_ROUTES,
  VARANASI_CHEAPEST_ROUTES,
  UTTARAKHAND_CHEAPEST_ROUTES,
  MADHYAPRADESH_CHEAPEST_ROUTES,
  RAJASTHAN_CHEAPEST_ROUTES,
  BIHAR_CHEAPEST_ROUTES,
  DELHI_NCR_CHEAPEST_ROUTES,
} from "./cheapestRoute";

export const ALL_ROUTES = [
  ...PRAYAGRAJ_CHEAPEST_ROUTES,
  ...AYODHYA_CHEAPEST_ROUTES,
  ...VARANASI_CHEAPEST_ROUTES,
  ...UTTARAKHAND_CHEAPEST_ROUTES,
  ...MADHYAPRADESH_CHEAPEST_ROUTES,
  ...RAJASTHAN_CHEAPEST_ROUTES,
  ...BIHAR_CHEAPEST_ROUTES,
  ...DELHI_NCR_CHEAPEST_ROUTES,
];