import { VEHICLES, TaxiRoute } from "./data";

export const PRAYAGRAJ_CHEAPEST_ROUTES: TaxiRoute[] = [
  {
    id: "pry-ayu",
    slug: "prayagraj-to-ayodhya-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Ayodhya",
    distance: 170,
    duration: "4 Hours",
    description:
      "Cheapest tempo traveller from Prayagraj to Ayodhya for Ram Mandir trips and family travel.",
    highlights: [
      "Cheapest Price",
      "Doorstep Pickup",
      "Same Day Return",
      "Safe Travel",
      "Transparent Pricing",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Ayodhya?",
        answer: "Fare starts from ₹" + 170 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "pry-vns",
    slug: "prayagraj-to-varanasi-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Varanasi",
    distance: 120,
    duration: "3 Hours",
    description:
      "Affordable tempo traveller from Prayagraj to Varanasi for group and religious trips.",
    highlights: [
      "Fast Route",
      "Budget Friendly",
      "Comfort Ride",
      "Experienced Drivers",
      "Flexible Timing",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Varanasi?",
        answer: "Fare starts from ₹" + 120 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "pry-lko",
    slug: "prayagraj-to-lucknow-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Lucknow",
    distance: 200,
    duration: "5 Hours",
    description:
      "Book cheapest tempo traveller from Prayagraj to Lucknow with best pricing.",
    highlights: [
      "Highway Route",
      "Clean Vehicles",
      "On Time",
      "Group Travel",
      "Affordable",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Lucknow?",
        answer: "Fare starts from ₹" + 200 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "pry-knp",
    slug: "prayagraj-to-kanpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Kanpur",
    distance: 210,
    duration: "5 Hours",
    description: "Cheap tempo traveller from Prayagraj to Kanpur.",
    highlights: ["Smooth Ride", "Affordable", "Safe", "24/7", "Trusted"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Kanpur?",
        answer: "Fare starts from ₹" + 210 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "pry-mzp",
    slug: "prayagraj-to-mirzapur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Mirzapur",
    distance: 90,
    duration: "2.5 Hours",
    description: "Budget tempo traveller from Prayagraj to Mirzapur.",
    highlights: ["Short Trip", "Low Cost", "Fast", "Local Drivers", "Safe"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Mirzapur?",
        answer: "Fare starts from ₹" + 90 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 100,
  },
  {
    id: "pry-jnp",
    slug: "prayagraj-to-jaunpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Jaunpur",
    distance: 110,
    duration: "3 Hours",
    description: "Affordable travel from Prayagraj to Jaunpur.",
    highlights: ["Comfort", "Flexible", "Budget", "Safe", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Jaunpur?",
        answer: "Fare starts from ₹" + 110 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 120,
  },
  {
    id: "pry-gkp",
    slug: "prayagraj-to-gorakhpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Gorakhpur",
    distance: 270,
    duration: "6.5 Hours",
    description: "Long distance cheapest tempo traveller to Gorakhpur.",
    highlights: ["Spacious", "Comfort", "Safe", "Long Trip", "Affordable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Gorakhpur?",
        answer: "Fare starts from ₹" + 270 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "pry-prtg",
    slug: "prayagraj-to-pratapgarh-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Pratapgarh",
    distance: 60,
    duration: "1.5 Hours",
    description: "Quick cheapest ride to Pratapgarh.",
    highlights: ["Short Route", "Low Cost", "Fast", "Easy Booking", "Safe"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Pratapgarh?",
        answer: "Fare starts from ₹" + 60 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 50,
  },
  {
    id: "pry-stn",
    slug: "prayagraj-to-satna-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Satna",
    distance: 140,
    duration: "3.5 Hours",
    description: "Affordable ride to Satna.",
    highlights: ["Comfort", "Highway", "Budget", "Safe", "Group"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Satna?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "pry-ctr",
    slug: "prayagraj-to-chitrakoot-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Chitrakoot",
    distance: 130,
    duration: "3.5 Hours",
    description: "Religious trip to Chitrakoot.",
    highlights: [
      "Pilgrimage",
      "Comfort",
      "Affordable",
      "Local Drivers",
      "Return",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Chitrakoot?",
        answer: "Fare starts from ₹" + 130 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "pry-lmp",
    slug: "prayagraj-to-lakhimpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Lakhimpur",
    distance: 320,
    duration: "7 Hours",
    description: "Affordable tempo traveller from Prayagraj to Lakhimpur.",
    highlights: ["Long Route", "Comfort", "Budget", "Safe", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Lakhimpur?",
        answer: "Fare starts from ₹" + 320 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "pry-sit",
    slug: "prayagraj-to-sitapur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Sitapur",
    distance: 300,
    duration: "6.5 Hours",
    description: "Budget travel from Prayagraj to Sitapur.",
    highlights: ["Budget", "Safe", "Comfort", "Group Travel", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Sitapur?",
        answer: "Fare starts from ₹" + 300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "pry-bly",
    slug: "prayagraj-to-bareilly-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Bareilly",
    distance: 380,
    duration: "8 Hours",
    description: "Long route cheapest ride to Bareilly.",
    highlights: ["Spacious", "Safe", "Long Trip", "Comfort", "Affordable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Bareilly?",
        answer: "Fare starts from ₹" + 380 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 650,
  },
  {
    id: "pry-agr",
    slug: "prayagraj-to-agra-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Agra",
    distance: 470,
    duration: "9 Hours",
    description: "Cheapest tempo traveller for Prayagraj to Agra trips.",
    highlights: ["Tour Route", "Comfort", "Safe", "Affordable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Agra?",
        answer: "Fare starts from ₹" + 470 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 800,
  },
  {
    id: "pry-del",
    slug: "prayagraj-to-delhi-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Delhi",
    distance: 700,
    duration: "12 Hours",
    description: "Book cheapest tempo traveller from Prayagraj to Delhi.",
    highlights: [
      "Long Distance",
      "Comfort",
      "Safe",
      "Night Travel",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Delhi?",
        answer: "Fare starts from ₹" + 700 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "pry-noi",
    slug: "prayagraj-to-noida-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Noida",
    distance: 680,
    duration: "11 Hours",
    description: "Affordable travel from Prayagraj to Noida.",
    highlights: ["Highway Route", "Comfort", "Safe", "Budget", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Noida?",
        answer: "Fare starts from ₹" + 680 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1100,
  },
  {
    id: "pry-fbd",
    slug: "prayagraj-to-faridabad-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Faridabad",
    distance: 720,
    duration: "12 Hours",
    description: "Budget tempo traveller from Prayagraj to Faridabad.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Faridabad?",
        answer: "Fare starts from ₹" + 720 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "pry-ghz",
    slug: "prayagraj-to-ghaziabad-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Ghaziabad",
    distance: 690,
    duration: "11.5 Hours",
    description: "Cheapest tempo traveller from Prayagraj to Ghaziabad.",
    highlights: ["Highway", "Comfort", "Safe", "Affordable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Ghaziabad?",
        answer: "Fare starts from ₹" + 690 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1100,
  },
  {
    id: "pry-hrd",
    slug: "prayagraj-to-haridwar-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Haridwar",
    distance: 800,
    duration: "14 Hours",
    description: "Religious trip from Prayagraj to Haridwar.",
    highlights: ["Pilgrimage", "Safe", "Comfort", "Long Trip", "Affordable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Haridwar?",
        answer: "Fare starts from ₹" + 800 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1400,
  },
  {
    id: "pry-rsh",
    slug: "prayagraj-to-rishikesh-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Rishikesh",
    distance: 820,
    duration: "14.5 Hours",
    description: "Affordable group travel from Prayagraj to Rishikesh.",
    highlights: ["Tour Route", "Comfort", "Safe", "Budget", "Long Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Rishikesh?",
        answer: "Fare starts from ₹" + 820 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
  {
    id: "pry-blr",
    slug: "prayagraj-to-ballia-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Ballia",
    distance: 240,
    duration: "6 Hours",
    description: "Affordable tempo traveller from Prayagraj to Ballia.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Ballia?",
        answer: "Fare starts from ₹" + 240 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "pry-ddu",
    slug: "prayagraj-to-mughalsarai-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Mughalsarai",
    distance: 130,
    duration: "3 Hours",
    description: "Budget ride from Prayagraj to Mughalsarai.",
    highlights: ["Fast Route", "Affordable", "Safe", "Comfort", "Easy Booking"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Mughalsarai?",
        answer: "Fare starts from ₹" + 130 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "pry-rtm",
    slug: "prayagraj-to-ratanpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Ratanpur",
    distance: 95,
    duration: "2.5 Hours",
    description: "Cheapest ride from Prayagraj to Ratanpur.",
    highlights: ["Short Trip", "Low Cost", "Fast", "Safe", "Local Drivers"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Ratanpur?",
        answer: "Fare starts from ₹" + 95 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 100,
  },
  {
    id: "pry-aur",
    slug: "prayagraj-to-auraiya-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Auraiya",
    distance: 230,
    duration: "5.5 Hours",
    description: "Affordable tempo traveller from Prayagraj to Auraiya.",
    highlights: ["Highway Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Auraiya?",
        answer: "Fare starts from ₹" + 230 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "pry-etw",
    slug: "prayagraj-to-etawah-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Etawah",
    distance: 300,
    duration: "6.5 Hours",
    description: "Budget travel from Prayagraj to Etawah.",
    highlights: ["Comfort", "Safe", "Affordable", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Etawah?",
        answer: "Fare starts from ₹" + 300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "pry-fth",
    slug: "prayagraj-to-fatehpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Fatehpur",
    distance: 120,
    duration: "3 Hours",
    description: "Affordable ride from Prayagraj to Fatehpur.",
    highlights: ["Short Route", "Budget", "Comfort", "Safe", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Fatehpur?",
        answer: "Fare starts from ₹" + 120 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 120,
  },
  {
    id: "pry-unnao",
    slug: "prayagraj-to-unnao-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Unnao",
    distance: 190,
    duration: "4.5 Hours",
    description: "Cheapest tempo traveller from Prayagraj to Unnao.",
    highlights: ["Comfort", "Affordable", "Safe", "Group Travel", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Unnao?",
        answer: "Fare starts from ₹" + 190 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "pry-sgr",
    slug: "prayagraj-to-singrauli-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Singrauli",
    distance: 260,
    duration: "6 Hours",
    description: "Affordable travel from Prayagraj to Singrauli.",
    highlights: ["Long Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Singrauli?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "pry-rew",
    slug: "prayagraj-to-rewa-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Rewa",
    distance: 150,
    duration: "3.5 Hours",
    description: "Budget-friendly tempo traveller from Prayagraj to Rewa.",
    highlights: ["Comfort", "Safe", "Affordable", "Highway", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Rewa?",
        answer: "Fare starts from ₹" + 150 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "pry-ktn",
    slug: "prayagraj-to-katni-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Katni",
    distance: 250,
    duration: "6 Hours",
    description: "Affordable ride from Prayagraj to Katni.",
    highlights: ["Comfort", "Safe", "Budget", "Long Trip", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Katni?",
        answer: "Fare starts from ₹" + 250 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "pry-mau",
    slug: "prayagraj-to-mau-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Mau",
    distance: 200,
    duration: "5 Hours",
    description: "Cheapest tempo traveller from Prayagraj to Mau.",
    highlights: ["Budget", "Comfort", "Safe", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Mau?",
        answer: "Fare starts from ₹" + 200 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "pry-bxr",
    slug: "prayagraj-to-buxar-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Buxar",
    distance: 140,
    duration: "3.5 Hours",
    description: "Affordable travel from Prayagraj to Buxar.",
    highlights: ["Short Route", "Fast", "Safe", "Budget", "Comfort"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Buxar?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "pry-arrah",
    slug: "prayagraj-to-arrah-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Arrah",
    distance: 200,
    duration: "5 Hours",
    description: "Budget tempo traveller from Prayagraj to Arrah.",
    highlights: ["Comfort", "Safe", "Affordable", "Reliable", "Group"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Arrah?",
        answer: "Fare starts from ₹" + 200 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "pry-pat",
    slug: "prayagraj-to-patna-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Patna",
    distance: 350,
    duration: "8 Hours",
    description: "Cheapest tempo traveller from Prayagraj to Patna.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Patna?",
        answer: "Fare starts from ₹" + 350 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 600,
  },
  {
    id: "pry-gya",
    slug: "prayagraj-to-gaya-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Gaya",
    distance: 360,
    duration: "8 Hours",
    description: "Affordable group travel from Prayagraj to Gaya.",
    highlights: ["Comfort", "Safe", "Budget", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Gaya?",
        answer: "Fare starts from ₹" + 360 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 600,
  },
  // ================= NEARBY ROUTES =================
  {
    id: "pry-kau",
    slug: "prayagraj-to-kaushambi-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Kaushambi",
    distance: 55,
    duration: "1.5 Hours",
    description: "Budget tempo traveller from Prayagraj to Kaushambi.",
    highlights: ["Short Trip", "Low Cost", "Fast", "Local Drivers", "Safe"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Kaushambi?",
        answer: "Fare starts from ₹" + 55 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 50,
  },
  {
    id: "pry-hnd",
    slug: "prayagraj-to-handia-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Handia",
    distance: 45,
    duration: "1 Hour",
    description: "Affordable ride from Prayagraj to Handia.",
    highlights: ["Short Route", "Budget", "Fast", "Safe", "Easy Booking"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Handia?",
        answer: "Fare starts from ₹" + 45 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 40,
  },
  {
    id: "pry-srt",
    slug: "prayagraj-to-sirathu-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Sirathu",
    distance: 60,
    duration: "1.5 Hours",
    description: "Cheap tempo traveller from Prayagraj to Sirathu.",
    highlights: ["Budget", "Safe", "Fast", "Comfort", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Sirathu?",
        answer: "Fare starts from ₹" + 60 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 50,
  },
  {
    id: "pry-phl",
    slug: "prayagraj-to-phulpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Phulpur",
    distance: 35,
    duration: "1 Hour",
    description: "Short trip from Prayagraj to Phulpur.",
    highlights: ["Low Cost", "Fast", "Local Route", "Safe", "Easy Booking"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Phulpur?",
        answer: "Fare starts from ₹" + 35 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 30,
  },
  {
    id: "pry-jhs",
    slug: "prayagraj-to-jhusi-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Jhusi",
    distance: 20,
    duration: "45 Min",
    description: "Quick ride from Prayagraj to Jhusi.",
    highlights: ["Very Short Trip", "Budget", "Fast", "Safe", "Local"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Jhusi?",
        answer: "Fare starts from ₹" + 20 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 20,
  },

  // ================= UP CITIES =================
  {
    id: "pry-sltn",
    slug: "prayagraj-to-sultanpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Sultanpur",
    distance: 160,
    duration: "4 Hours",
    description: "Affordable travel from Prayagraj to Sultanpur.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Sultanpur?",
        answer: "Fare starts from ₹" + 160 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "pry-rbl",
    slug: "prayagraj-to-raebareli-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Raebareli",
    distance: 180,
    duration: "4.5 Hours",
    description: "Budget ride from Prayagraj to Raebareli.",
    highlights: ["Affordable", "Comfort", "Safe", "Highway", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Raebareli?",
        answer: "Fare starts from ₹" + 180 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "pry-amth",
    slug: "prayagraj-to-amethi-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Amethi",
    distance: 170,
    duration: "4 Hours",
    description: "Affordable tempo traveller from Prayagraj to Amethi.",
    highlights: ["Budget", "Safe", "Comfort", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Amethi?",
        answer: "Fare starts from ₹" + 170 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "pry-mrt",
    slug: "prayagraj-to-meerut-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Meerut",
    distance: 750,
    duration: "13 Hours",
    description: "Long route from Prayagraj to Meerut.",
    highlights: ["Long Trip", "Comfort", "Safe", "Highway", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Meerut?",
        answer: "Fare starts from ₹" + 750 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },

  // ================= RELIGIOUS =================
  {
    id: "pry-vnd",
    slug: "prayagraj-to-vindhyachal-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Vindhyachal",
    distance: 90,
    duration: "2.5 Hours",
    description: "Religious trip from Prayagraj to Vindhyachal.",
    highlights: ["Pilgrimage", "Safe", "Budget", "Comfort", "Fast"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Vindhyachal?",
        answer: "Fare starts from ₹" + 90 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 100,
  },
  {
    id: "pry-vrn",
    slug: "prayagraj-to-vrindavan-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Vrindavan",
    distance: 480,
    duration: "9 Hours",
    description: "Spiritual trip from Prayagraj to Vrindavan.",
    highlights: [
      "Temple Visit",
      "Comfort",
      "Safe",
      "Affordable",
      "Group Travel",
    ],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Vrindavan?",
        answer: "Fare starts from ₹" + 480 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 800,
  },
  {
    id: "pry-gvr",
    slug: "prayagraj-to-govardhan-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Govardhan",
    distance: 500,
    duration: "9.5 Hours",
    description: "Religious trip to Govardhan from Prayagraj.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Govardhan?",
        answer: "Fare starts from ₹" + 500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 850,
  },

  // ================= OTHER STATES =================
  {
    id: "pry-jbp",
    slug: "prayagraj-to-jabalpur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Jabalpur",
    distance: 350,
    duration: "8 Hours",
    description: "Affordable ride to Jabalpur.",
    highlights: ["Comfort", "Safe", "Budget", "Highway", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Jabalpur?",
        answer: "Fare starts from ₹" + 350 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "pry-mhr",
    slug: "prayagraj-to-maihar-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Maihar",
    distance: 180,
    duration: "4.5 Hours",
    description: "Religious trip to Maihar Mata temple.",
    highlights: ["Temple Visit", "Safe", "Budget", "Comfort", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Maihar?",
        answer: "Fare starts from ₹" + 180 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },

  // ================= PREMIUM =================
  {
    id: "pry-jpr",
    slug: "prayagraj-to-jaipur-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Jaipur",
    distance: 750,
    duration: "14 Hours",
    description: "Premium long trip from Prayagraj to Jaipur.",
    highlights: ["Luxury", "Comfort", "Safe", "Long Trip", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Jaipur?",
        answer: "Fare starts from ₹" + 750 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1300,
  },
  {
    id: "pry-ddn",
    slug: "prayagraj-to-dehradun-cheapest-tempo-traveller-fare",
    origin: "Prayagraj",
    destination: "Dehradun",
    distance: 850,
    duration: "15 Hours",
    description: "Long distance travel from Prayagraj to Dehradun.",
    highlights: ["Hill Travel", "Comfort", "Safe", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Prayagraj to Dehradun?",
        answer: "Fare starts from ₹" + 850 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
];

export const AYODHYA_CHEAPEST_ROUTES: TaxiRoute[] = [
  {
    id: "ayu-pry",
    slug: "ayodhya-to-prayagraj-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Prayagraj",
    distance: 170,
    duration: "4 Hours",
    description:
      "Book cheapest tempo traveller from Ayodhya to Prayagraj for comfortable group travel.",
    highlights: [
      "Cheapest Price",
      "Doorstep Pickup",
      "Same Day Return",
      "Safe Travel",
      "Transparent Pricing",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Prayagraj?",
        answer: "Fare starts from ₹" + 170 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "ayu-vns",
    slug: "ayodhya-to-varanasi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Varanasi",
    distance: 220,
    duration: "4.5 Hours",
    description:
      "Affordable tempo traveller from Ayodhya to Varanasi for spiritual and group trips.",
    highlights: [
      "Via Purvanchal Expressway",
      "Comfort Ride",
      "Flexible Timing",
      "Experienced Drivers",
      "Budget Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Varanasi?",
        answer: "Fare starts from ₹" + 220 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "ayu-lko",
    slug: "ayodhya-to-lucknow-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Lucknow",
    distance: 135,
    duration: "3.5 Hours",
    description:
      "Cheapest tempo traveller from Ayodhya to Lucknow with smooth highway travel.",
    highlights: [
      "Highway Route",
      "Clean Vehicles",
      "On Time Service",
      "Group Friendly",
      "Affordable Pricing",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Lucknow?",
        answer: "Fare starts from ₹" + 135 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-gkp",
    slug: "ayodhya-to-gorakhpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Gorakhpur",
    distance: 140,
    duration: "3.5 Hours",
    description:
      "Budget-friendly tempo traveller from Ayodhya to Gorakhpur for group travel.",
    highlights: [
      "Comfort Travel",
      "Affordable Fare",
      "Safe Ride",
      "Local Drivers",
      "Quick Booking",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Gorakhpur?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-bst",
    slug: "ayodhya-to-basti-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Basti",
    distance: 70,
    duration: "2 Hours",
    description: "Quick and cheapest tempo traveller from Ayodhya to Basti.",
    highlights: [
      "Short Route",
      "Low Cost",
      "Fast Travel",
      "Easy Booking",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Basti?",
        answer: "Fare starts from ₹" + 70 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 100,
  },
  {
    id: "ayu-slp",
    slug: "ayodhya-to-sultanpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Sultanpur",
    distance: 110,
    duration: "3 Hours",
    description: "Affordable group travel from Ayodhya to Sultanpur.",
    highlights: [
      "Budget Friendly",
      "Comfortable Ride",
      "Safe Travel",
      "Flexible Timing",
      "Trusted Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Sultanpur?",
        answer: "Fare starts from ₹" + 110 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "ayu-fzd",
    slug: "ayodhya-to-faizabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Faizabad",
    distance: 10,
    duration: "30 Minutes",
    description: "Very short and cheapest ride from Ayodhya to Faizabad.",
    highlights: [
      "Ultra Short Trip",
      "Lowest Price",
      "Quick Pickup",
      "Local Drivers",
      "Fast Service",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Faizabad?",
        answer: "Fare starts from ₹" + 10 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 0,
  },
  {
    id: "ayu-amethi",
    slug: "ayodhya-to-amethi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Amethi",
    distance: 140,
    duration: "4 Hours",
    description:
      "Cheapest tempo traveller from Ayodhya to Amethi for group journeys.",
    highlights: [
      "Comfort Travel",
      "Affordable Pricing",
      "Safe Ride",
      "Group Friendly",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Amethi?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "ayu-prtg",
    slug: "ayodhya-to-pratapgarh-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Pratapgarh",
    distance: 160,
    duration: "4 Hours",
    description:
      "Affordable travel from Ayodhya to Pratapgarh with tempo traveller.",
    highlights: [
      "Smooth Route",
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "On Time Service",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Pratapgarh?",
        answer: "Fare starts from ₹" + 160 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-knp",
    slug: "ayodhya-to-kanpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Kanpur",
    distance: 230,
    duration: "5.5 Hours",
    description:
      "Book cheapest tempo traveller from Ayodhya to Kanpur for long-distance group travel.",
    highlights: [
      "Long Distance Comfort",
      "Experienced Drivers",
      "Safe Travel",
      "Affordable Rates",
      "Group Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Kanpur?",
        answer: "Fare starts from ₹" + 230 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "ayu-bly",
    slug: "ayodhya-to-bareilly-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Bareilly",
    distance: 320,
    duration: "7 Hours",
    description: "Affordable tempo traveller from Ayodhya to Bareilly.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Bareilly?",
        answer: "Fare starts from ₹" + 320 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "ayu-sit",
    slug: "ayodhya-to-sitapur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Sitapur",
    distance: 220,
    duration: "5 Hours",
    description: "Budget-friendly travel from Ayodhya to Sitapur.",
    highlights: ["Budget", "Comfort", "Safe", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Sitapur?",
        answer: "Fare starts from ₹" + 220 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "ayu-lmp",
    slug: "ayodhya-to-lakhimpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Lakhimpur",
    distance: 260,
    duration: "6 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Lakhimpur.",
    highlights: ["Comfort", "Safe", "Affordable", "Long Trip", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Lakhimpur?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "ayu-gda",
    slug: "ayodhya-to-gonda-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Gonda",
    distance: 60,
    duration: "1.5 Hours",
    description: "Quick and affordable ride from Ayodhya to Gonda.",
    highlights: ["Short Route", "Low Cost", "Fast", "Safe", "Easy Booking"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Gonda?",
        answer: "Fare starts from ₹" + 60 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 80,
  },
  {
    id: "ayu-blr",
    slug: "ayodhya-to-ballia-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ballia",
    distance: 260,
    duration: "6 Hours",
    description: "Affordable group travel from Ayodhya to Ballia.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ballia?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "ayu-mau",
    slug: "ayodhya-to-mau-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Mau",
    distance: 180,
    duration: "4.5 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Mau.",
    highlights: ["Comfort", "Safe", "Affordable", "Fast", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Mau?",
        answer: "Fare starts from ₹" + 180 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-azm",
    slug: "ayodhya-to-azamgarh-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Azamgarh",
    distance: 160,
    duration: "4 Hours",
    description: "Budget tempo traveller from Ayodhya to Azamgarh.",
    highlights: [
      "Budget Friendly",
      "Comfort",
      "Safe",
      "Flexible Timing",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Azamgarh?",
        answer: "Fare starts from ₹" + 160 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "ayu-bxr",
    slug: "ayodhya-to-buxar-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Buxar",
    distance: 240,
    duration: "6 Hours",
    description: "Affordable travel from Ayodhya to Buxar.",
    highlights: ["Long Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Buxar?",
        answer: "Fare starts from ₹" + 240 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "ayu-pat",
    slug: "ayodhya-to-patna-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Patna",
    distance: 300,
    duration: "7 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Patna.",
    highlights: ["Long Distance", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Patna?",
        answer: "Fare starts from ₹" + 300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "ayu-gya",
    slug: "ayodhya-to-gaya-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Gaya",
    distance: 320,
    duration: "7.5 Hours",
    description: "Affordable group travel from Ayodhya to Gaya.",
    highlights: ["Comfort", "Safe", "Budget", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Gaya?",
        answer: "Fare starts from ₹" + 320 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 550,
  },
  {
    id: "ayu-jhs",
    slug: "ayodhya-to-jhansi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Jhansi",
    distance: 420,
    duration: "9 Hours",
    description: "Affordable tempo traveller from Ayodhya to Jhansi.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Jhansi?",
        answer: "Fare starts from ₹" + 420 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 700,
  },
  {
    id: "ayu-banda",
    slug: "ayodhya-to-banda-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Banda",
    distance: 300,
    duration: "7 Hours",
    description: "Budget travel from Ayodhya to Banda.",
    highlights: ["Budget", "Comfort", "Safe", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Banda?",
        answer: "Fare starts from ₹" + 300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "ayu-deoria",
    slug: "ayodhya-to-deoria-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Deoria",
    distance: 170,
    duration: "4 Hours",
    description: "Affordable ride from Ayodhya to Deoria.",
    highlights: ["Comfort", "Safe", "Affordable", "Fast", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Deoria?",
        answer: "Fare starts from ₹" + 170 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-kushinagar",
    slug: "ayodhya-to-kushinagar-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Kushinagar",
    distance: 190,
    duration: "4.5 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Kushinagar.",
    highlights: ["Religious Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Kushinagar?",
        answer: "Fare starts from ₹" + 190 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 280,
  },
  {
    id: "ayu-bhadohi",
    slug: "ayodhya-to-bhadohi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Bhadohi",
    distance: 210,
    duration: "5 Hours",
    description: "Affordable tempo traveller from Ayodhya to Bhadohi.",
    highlights: ["Budget", "Comfort", "Safe", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Bhadohi?",
        answer: "Fare starts from ₹" + 210 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "ayu-sonbhadra",
    slug: "ayodhya-to-sonbhadra-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Sonbhadra",
    distance: 320,
    duration: "7 Hours",
    description: "Long distance ride from Ayodhya to Sonbhadra.",
    highlights: ["Long Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Sonbhadra?",
        answer: "Fare starts from ₹" + 320 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "ayu-varanasi-airport",
    slug: "ayodhya-to-varanasi-airport-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Varanasi Airport",
    distance: 230,
    duration: "5 Hours",
    description: "Airport transfer from Ayodhya to Varanasi Airport.",
    highlights: ["Airport Pickup", "On Time", "Comfort", "Safe", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Varanasi Airport?",
        answer: "Fare starts from ₹" + 230 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "ayu-lucknow-airport",
    slug: "ayodhya-to-lucknow-airport-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Lucknow Airport",
    distance: 140,
    duration: "3.5 Hours",
    description: "Airport transfer from Ayodhya to Lucknow Airport.",
    highlights: ["Airport Drop", "Comfort", "Safe", "Affordable", "On Time"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Lucknow Airport?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "ayu-delhi",
    slug: "ayodhya-to-delhi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Delhi",
    distance: 650,
    duration: "11 Hours",
    description: "Long distance travel from Ayodhya to Delhi.",
    highlights: ["Night Travel", "Comfort", "Safe", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Delhi?",
        answer: "Fare starts from ₹" + 650 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1100,
  },
  {
    id: "ayu-noida",
    slug: "ayodhya-to-noida-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Noida",
    distance: 640,
    duration: "11 Hours",
    description: "Affordable travel from Ayodhya to Noida.",
    highlights: ["Highway Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Noida?",
        answer: "Fare starts from ₹" + 640 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1100,
  },
  {
    id: "ayu-gurgaon",
    slug: "ayodhya-to-gurgaon-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Gurgaon",
    distance: 670,
    duration: "12 Hours",
    description: "Book tempo traveller from Ayodhya to Gurgaon.",
    highlights: [
      "Corporate Travel",
      "Comfort",
      "Safe",
      "Reliable",
      "Affordable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Gurgaon?",
        answer: "Fare starts from ₹" + 670 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "ayu-jaipur",
    slug: "ayodhya-to-jaipur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Jaipur",
    distance: 750,
    duration: "13 Hours",
    description: "Long route travel from Ayodhya to Jaipur.",
    highlights: ["Tour Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Jaipur?",
        answer: "Fare starts from ₹" + 750 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1300,
  },
  {
    id: "ayu-bhopal",
    slug: "ayodhya-to-bhopal-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Bhopal",
    distance: 700,
    duration: "12 Hours",
    description: "Affordable travel from Ayodhya to Bhopal.",
    highlights: ["Long Route", "Comfort", "Safe", "Reliable", "Budget"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Bhopal?",
        answer: "Fare starts from ₹" + 700 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "ayu-indore",
    slug: "ayodhya-to-indore-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Indore",
    distance: 900,
    duration: "15 Hours",
    description: "Premium long distance route from Ayodhya to Indore.",
    highlights: ["Premium Route", "Comfort", "Safe", "Long Travel", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Indore?",
        answer: "Fare starts from ₹" + 900 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1600,
  },
  {
    id: "ayu-mumbai",
    slug: "ayodhya-to-mumbai-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Mumbai",
    distance: 1400,
    duration: "24 Hours",
    description: "Very long distance travel from Ayodhya to Mumbai.",
    highlights: ["Ultra Long Route", "Comfort", "Safe", "Premium", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Mumbai?",
        answer: "Fare starts from ₹" + 1400 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2500,
  },
  {
    id: "ayu-kolkata",
    slug: "ayodhya-to-kolkata-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Kolkata",
    distance: 900,
    duration: "16 Hours",
    description: "Affordable long route from Ayodhya to Kolkata.",
    highlights: ["Long Route", "Comfort", "Safe", "Reliable", "Affordable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Kolkata?",
        answer: "Fare starts from ₹" + 900 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
  {
    id: "ayu-hyderabad",
    slug: "ayodhya-to-hyderabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Hyderabad",
    distance: 1500,
    duration: "26 Hours",
    description: "Long distance group travel from Ayodhya to Hyderabad.",
    highlights: ["Ultra Long Route", "Comfort", "Safe", "Premium", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Hyderabad?",
        answer: "Fare starts from ₹" + 1500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2600,
  },
  {
    id: "ayu-dhanbad",
    slug: "ayodhya-to-dhanbad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Dhanbad",
    distance: 600,
    duration: "12 Hours",
    description: "Affordable travel from Ayodhya to Dhanbad.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Dhanbad?",
        answer: "Fare starts from ₹" + 600 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1000,
  },
  {
    id: "ayu-balrampur",
    slug: "ayodhya-to-balrampur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Balrampur",
    distance: 120,
    duration: "3 Hours",
    description: "Budget travel from Ayodhya to Balrampur.",
    highlights: ["Budget", "Comfort", "Safe", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Balrampur?",
        answer: "Fare starts from ₹" + 120 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "ayu-bahraich",
    slug: "ayodhya-to-bahraich-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Bahraich",
    distance: 160,
    duration: "4 Hours",
    description: "Affordable ride from Ayodhya to Bahraich.",
    highlights: ["Comfort", "Safe", "Affordable", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Bahraich?",
        answer: "Fare starts from ₹" + 160 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "ayu-ambedkar",
    slug: "ayodhya-to-ambedkar-nagar-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ambedkar Nagar",
    distance: 90,
    duration: "2.5 Hours",
    description: "Cheap tempo traveller from Ayodhya to Ambedkar Nagar.",
    highlights: ["Short Route", "Affordable", "Safe", "Fast", "Comfort"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ambedkar Nagar?",
        answer: "Fare starts from ₹" + 90 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 120,
  },
  {
    id: "ayu-barabanki",
    slug: "ayodhya-to-barabanki-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Barabanki",
    distance: 110,
    duration: "3 Hours",
    description: "Affordable travel from Ayodhya to Barabanki.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Barabanki?",
        answer: "Fare starts from ₹" + 110 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "ayu-raebareli",
    slug: "ayodhya-to-raebareli-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Raebareli",
    distance: 150,
    duration: "4 Hours",
    description: "Budget-friendly travel from Ayodhya to Raebareli.",
    highlights: ["Comfort", "Safe", "Affordable", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Raebareli?",
        answer: "Fare starts from ₹" + 150 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "ayu-shravasti",
    slug: "ayodhya-to-shravasti-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Shravasti",
    distance: 130,
    duration: "3.5 Hours",
    description: "Religious and budget travel from Ayodhya to Shravasti.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Shravasti?",
        answer: "Fare starts from ₹" + 130 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 180,
  },
  {
    id: "ayu-ghazipur",
    slug: "ayodhya-to-ghazipur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ghazipur",
    distance: 210,
    duration: "5 Hours",
    description: "Affordable travel from Ayodhya to Ghazipur.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ghazipur?",
        answer: "Fare starts from ₹" + 210 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "ayu-vindhyachal",
    slug: "ayodhya-to-vindhyachal-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Vindhyachal",
    distance: 260,
    duration: "6 Hours",
    description: "Religious trip from Ayodhya to Vindhyachal.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Vindhyachal?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "ayu-sitamarhi",
    slug: "ayodhya-to-sitamarhi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Sitamarhi",
    distance: 350,
    duration: "8 Hours",
    description: "Religious travel from Ayodhya to Sitamarhi.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Sitamarhi?",
        answer: "Fare starts from ₹" + 350 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "ayu-arrah",
    slug: "ayodhya-to-arrah-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Arrah",
    distance: 260,
    duration: "6 Hours",
    description: "Affordable travel from Ayodhya to Arrah.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Fast"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Arrah?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "ayu-jabalpur",
    slug: "ayodhya-to-jabalpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Jabalpur",
    distance: 500,
    duration: "10 Hours",
    description: "Long route from Ayodhya to Jabalpur.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Jabalpur?",
        answer: "Fare starts from ₹" + 500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 800,
  },
  {
    id: "ayu-dehradun",
    slug: "ayodhya-to-dehradun-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Dehradun",
    distance: 800,
    duration: "14 Hours",
    description: "Premium travel from Ayodhya to Dehradun.",
    highlights: ["Long Route", "Comfort", "Safe", "Premium", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Dehradun?",
        answer: "Fare starts from ₹" + 800 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1400,
  },
  {
    id: "ayu-ghz",
    slug: "ayodhya-to-ghaziabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ghaziabad",
    distance: 680,
    duration: "11.5 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Ghaziabad.",
    highlights: ["Fast Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ghaziabad?",
        answer: "Fare starts from ₹" + 680 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1100,
  },
  {
    id: "ayu-fbd",
    slug: "ayodhya-to-faridabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Faridabad",
    distance: 710,
    duration: "12 Hours",
    description: "Affordable tempo traveller from Ayodhya to Faridabad.",
    highlights: ["Long Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Faridabad?",
        answer: "Fare starts from ₹" + 710 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "ayu-hrd",
    slug: "ayodhya-to-haridwar-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Haridwar",
    distance: 780,
    duration: "14 Hours",
    description: "Religious trip from Ayodhya to Haridwar.",
    highlights: ["Pilgrimage", "Safe", "Comfort", "Affordable", "Long Trip"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Haridwar?",
        answer: "Fare starts from ₹" + 780 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1400,
  },
  {
    id: "ayu-rsh",
    slug: "ayodhya-to-rishikesh-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Rishikesh",
    distance: 800,
    duration: "14.5 Hours",
    description: "Affordable group travel from Ayodhya to Rishikesh.",
    highlights: ["Tour Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Rishikesh?",
        answer: "Fare starts from ₹" + 800 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
  {
    id: "ayu-chd",
    slug: "ayodhya-to-chandigarh-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Chandigarh",
    distance: 950,
    duration: "16 Hours",
    description:
      "Long-distance cheapest tempo traveller from Ayodhya to Chandigarh.",
    highlights: ["Long Route", "Comfort", "Safe", "Premium Travel", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Chandigarh?",
        answer: "Fare starts from ₹" + 950 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1600,
  },
  {
    id: "ayu-alh",
    slug: "ayodhya-to-aligarh-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Aligarh",
    distance: 550,
    duration: "10 Hours",
    description: "Affordable tempo traveller from Ayodhya to Aligarh.",
    highlights: ["Comfort", "Safe", "Budget", "Reliable", "Long Route"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Aligarh?",
        answer: "Fare starts from ₹" + 550 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 900,
  },
  {
    id: "ayu-mrt",
    slug: "ayodhya-to-meerut-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Meerut",
    distance: 720,
    duration: "12 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Meerut.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Meerut?",
        answer: "Fare starts from ₹" + 720 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1200,
  },
  {
    id: "ayu-sre",
    slug: "ayodhya-to-saharanpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Saharanpur",
    distance: 850,
    duration: "14 Hours",
    description: "Affordable travel from Ayodhya to Saharanpur.",
    highlights: ["Long Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Saharanpur?",
        answer: "Fare starts from ₹" + 850 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1400,
  },
  {
    id: "ayu-mth",
    slug: "ayodhya-to-mathura-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Mathura",
    distance: 620,
    duration: "11 Hours",
    description: "Religious trip from Ayodhya to Mathura.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Group Travel"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Mathura?",
        answer: "Fare starts from ₹" + 620 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1000,
  },
  {
    id: "ayu-vrd",
    slug: "ayodhya-to-vrindavan-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Vrindavan",
    distance: 630,
    duration: "11 Hours",
    description: "Affordable tempo traveller from Ayodhya to Vrindavan.",
    highlights: ["Religious Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Vrindavan?",
        answer: "Fare starts from ₹" + 630 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1000,
  },
  {
    id: "ayu-jhs",
    slug: "ayodhya-to-jhansi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Jhansi",
    distance: 500,
    duration: "9 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Jhansi.",
    highlights: ["Comfort", "Safe", "Affordable", "Highway Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Jhansi?",
        answer: "Fare starts from ₹" + 500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 800,
  },
  {
    id: "ayu-ork",
    slug: "ayodhya-to-orchha-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Orchha",
    distance: 520,
    duration: "9.5 Hours",
    description: "Affordable travel from Ayodhya to Orchha.",
    highlights: ["Tour Route", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Orchha?",
        answer: "Fare starts from ₹" + 520 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 850,
  },
  {
    id: "ayu-ngp",
    slug: "ayodhya-to-nagpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Nagpur",
    distance: 1000,
    duration: "17 Hours",
    description: "Affordable long-distance travel from Ayodhya to Nagpur.",
    highlights: [
      "Very Long Route",
      "Comfort",
      "Safe",
      "Affordable",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Nagpur?",
        answer: "Fare starts from ₹" + 1000 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1700,
  },
  {
    id: "ayu-rnc",
    slug: "ayodhya-to-ranchi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ranchi",
    distance: 750,
    duration: "14 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Ranchi.",
    highlights: ["Comfort", "Safe", "Affordable", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ranchi?",
        answer: "Fare starts from ₹" + 750 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1300,
  },
  {
    id: "ayu-jdp",
    slug: "ayodhya-to-jagdalpur-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Jagdalpur",
    distance: 1100,
    duration: "20 Hours",
    description: "Very long route tempo traveller from Ayodhya to Jagdalpur.",
    highlights: [
      "Extreme Long Route",
      "Comfort",
      "Safe",
      "Premium Travel",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Jagdalpur?",
        answer: "Fare starts from ₹" + 1100 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1800,
  },
  {
    id: "ayu-amd",
    slug: "ayodhya-to-ahmedabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ahmedabad",
    distance: 1400,
    duration: "24 Hours",
    description: "Premium tempo traveller from Ayodhya to Ahmedabad.",
    highlights: [
      "Premium Route",
      "Comfort",
      "Safe",
      "Very Long Travel",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ahmedabad?",
        answer: "Fare starts from ₹" + 1400 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2500,
  },
  {
    id: "ayu-sur",
    slug: "ayodhya-to-surat-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Surat",
    distance: 1500,
    duration: "26 Hours",
    description: "Long-distance travel from Ayodhya to Surat.",
    highlights: ["Premium", "Comfort", "Safe", "Long Route", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Surat?",
        answer: "Fare starts from ₹" + 1500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2600,
  },
  {
    id: "ayu-pun",
    slug: "ayodhya-to-pune-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Pune",
    distance: 1550,
    duration: "27 Hours",
    description: "Affordable travel from Ayodhya to Pune.",
    highlights: ["Long Route", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Pune?",
        answer: "Fare starts from ₹" + 1550 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2700,
  },
  {
    id: "ayu-hyd",
    slug: "ayodhya-to-hyderabad-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Hyderabad",
    distance: 1300,
    duration: "22 Hours",
    description: "Long-distance tempo traveller from Ayodhya to Hyderabad.",
    highlights: ["Premium", "Comfort", "Safe", "Long Travel", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Hyderabad?",
        answer: "Fare starts from ₹" + 1300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2200,
  },
  {
    id: "ayu-blr",
    slug: "ayodhya-to-bangalore-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Bangalore",
    distance: 1900,
    duration: "32 Hours",
    description: "Premium tempo traveller from Ayodhya to Bangalore.",
    highlights: [
      "Extreme Long Route",
      "Comfort",
      "Safe",
      "Luxury Travel",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Bangalore?",
        answer: "Fare starts from ₹" + 1900 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 3200,
  },
  {
    id: "ayu-che",
    slug: "ayodhya-to-chennai-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Chennai",
    distance: 2100,
    duration: "36 Hours",
    description: "Cheapest tempo traveller from Ayodhya to Chennai.",
    highlights: [
      "Extreme Long Route",
      "Comfort",
      "Safe",
      "Premium Travel",
      "Reliable",
    ],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Chennai?",
        answer: "Fare starts from ₹" + 2100 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 3500,
  },
  {
    id: "ayu-goa",
    slug: "ayodhya-to-goa-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Goa",
    distance: 2000,
    duration: "34 Hours",
    description: "Affordable long-distance travel from Ayodhya to Goa.",
    highlights: ["Tour Route", "Comfort", "Safe", "Premium", "Long Travel"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Goa?",
        answer: "Fare starts from ₹" + 2000 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 3300,
  },
  {
    id: "ayu-shr",
    slug: "ayodhya-to-shirdi-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Shirdi",
    distance: 1500,
    duration: "26 Hours",
    description: "Religious trip from Ayodhya to Shirdi.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Shirdi?",
        answer: "Fare starts from ₹" + 1500 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 2600,
  },
  {
    id: "ayu-ujj",
    slug: "ayodhya-to-ujjain-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Ujjain",
    distance: 850,
    duration: "15 Hours",
    description: "Religious travel from Ayodhya to Ujjain.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Affordable", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Ujjain?",
        answer: "Fare starts from ₹" + 850 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1400,
  },
  {
    id: "ayu-omk",
    slug: "ayodhya-to-omkareshwar-cheapest-tempo-traveller-fare",
    origin: "Ayodhya",
    destination: "Omkareshwar",
    distance: 900,
    duration: "16 Hours",
    description: "Affordable religious travel from Ayodhya to Omkareshwar.",
    highlights: ["Pilgrimage", "Comfort", "Safe", "Budget", "Reliable"],
    faqs: [
      {
        question: "What is the fare from Ayodhya to Omkareshwar?",
        answer: "Fare starts from ₹" + 900 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
];

export const VARANASI_CHEAPEST_ROUTES: TaxiRoute[] = [
  {
    id: "vns-ayu",
    slug: "varanasi-to-ayodhya-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Ayodhya",
    distance: 220,
    duration: "4.5 Hours",
    description:
      "Book cheapest tempo traveller from Varanasi to Ayodhya for Ram Mandir and group trips.",
    highlights: [
      "Cheapest Price",
      "Via Purvanchal Expressway",
      "Same Day Return",
      "Comfort Travel",
      "Transparent Pricing",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Ayodhya?",
        answer: "Fare starts from ₹" + 220 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "vns-pry",
    slug: "varanasi-to-prayagraj-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Prayagraj",
    distance: 120,
    duration: "3 Hours",
    description:
      "Affordable tempo traveller from Varanasi to Prayagraj for group and religious travel.",
    highlights: [
      "Fast Route",
      "Budget Friendly",
      "Comfort Ride",
      "Flexible Timing",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Prayagraj?",
        answer: "Fare starts from ₹" + 120 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "vns-gzp",
    slug: "varanasi-to-ghazipur-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Ghazipur",
    distance: 80,
    duration: "2 Hours",
    description: "Budget-friendly tempo traveller from Varanasi to Ghazipur.",
    highlights: [
      "Short Route",
      "Low Cost",
      "Quick Travel",
      "Local Drivers",
      "Safe Ride",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Ghazipur?",
        answer: "Fare starts from ₹" + 80 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 100,
  },
  {
    id: "vns-mzp",
    slug: "varanasi-to-mirzapur-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Mirzapur",
    distance: 65,
    duration: "1.5 Hours",
    description:
      "Cheapest tempo traveller from Varanasi to Mirzapur for short trips.",
    highlights: [
      "Quick Trip",
      "Affordable Fare",
      "Comfort Ride",
      "Easy Booking",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Mirzapur?",
        answer: "Fare starts from ₹" + 65 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 80,
  },
  {
    id: "vns-jnp",
    slug: "varanasi-to-jaunpur-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Jaunpur",
    distance: 60,
    duration: "1.5 Hours",
    description:
      "Affordable travel from Varanasi to Jaunpur with tempo traveller.",
    highlights: [
      "Budget Friendly",
      "Short Distance",
      "Safe Travel",
      "Comfort Ride",
      "Trusted Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Jaunpur?",
        answer: "Fare starts from ₹" + 60 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 80,
  },
  {
    id: "vns-bhd",
    slug: "varanasi-to-bhadohi-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Bhadohi",
    distance: 45,
    duration: "1 Hour",
    description: "Cheapest short-distance ride from Varanasi to Bhadohi.",
    highlights: [
      "Lowest Fare",
      "Quick Pickup",
      "Short Route",
      "Local Drivers",
      "Fast Travel",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Bhadohi?",
        answer: "Fare starts from ₹" + 45 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 50,
  },
  {
    id: "vns-gkp",
    slug: "varanasi-to-gorakhpur-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Gorakhpur",
    distance: 220,
    duration: "5 Hours",
    description:
      "Long-distance cheapest tempo traveller from Varanasi to Gorakhpur.",
    highlights: [
      "Long Route Comfort",
      "Spacious Seating",
      "Safe Travel",
      "Affordable Pricing",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Gorakhpur?",
        answer: "Fare starts from ₹" + 220 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "vns-azm",
    slug: "varanasi-to-azamgarh-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Azamgarh",
    distance: 100,
    duration: "2.5 Hours",
    description: "Affordable tempo traveller from Varanasi to Azamgarh.",
    highlights: [
      "Comfort Travel",
      "Budget Friendly",
      "Safe Ride",
      "Flexible Timing",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Azamgarh?",
        answer: "Fare starts from ₹" + 100 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 120,
  },
  {
    id: "vns-srn",
    slug: "varanasi-to-sarnath-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Sarnath",
    distance: 12,
    duration: "30 Minutes",
    description: "Very short and cheapest ride from Varanasi to Sarnath.",
    highlights: [
      "Ultra Short Trip",
      "Lowest Price",
      "Quick Pickup",
      "Local Drivers",
      "Fast Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Sarnath?",
        answer: "Fare starts from ₹" + 12 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 0,
  },
  {
    id: "vns-lko",
    slug: "varanasi-to-lucknow-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Lucknow",
    distance: 320,
    duration: "6.5 Hours",
    description:
      "Book cheapest tempo traveller from Varanasi to Lucknow for long-distance group travel.",
    highlights: [
      "Highway Route",
      "Comfortable Ride",
      "Experienced Drivers",
      "Safe Travel",
      "Affordable Rates",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Lucknow?",
        answer: "Fare starts from ₹" + 320 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "vns-bodh",
    slug: "varanasi-to-bodhgaya-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Bodhgaya",
    distance: 250,
    duration: "6 Hours",
    description:
      "Affordable tempo traveller from Varanasi to Bodhgaya for spiritual tours.",
    highlights: [
      "Buddhist Circuit",
      "Comfort Ride",
      "Budget Friendly",
      "Experienced Drivers",
      "Safe Travel",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Bodhgaya?",
        answer: "Fare starts from ₹" + 250 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "vns-mgs",
    slug: "varanasi-to-mughalsarai-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Mughalsarai",
    distance: 20,
    duration: "40 Minutes",
    description: "Quick and cheapest ride from Varanasi to Mughalsarai.",
    highlights: [
      "Short Trip",
      "Low Cost",
      "Quick Pickup",
      "Local Drivers",
      "Fast Travel",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Mughalsarai?",
        answer: "Fare starts from ₹" + 20 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 0,
  },
  {
    id: "vns-bxr",
    slug: "varanasi-to-buxar-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Buxar",
    distance: 130,
    duration: "3 Hours",
    description: "Budget-friendly tempo traveller from Varanasi to Buxar.",
    highlights: [
      "Affordable",
      "Comfort Ride",
      "Safe Travel",
      "Flexible Timing",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Buxar?",
        answer: "Fare starts from ₹" + 130 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "vns-ara",
    slug: "varanasi-to-ara-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Ara",
    distance: 170,
    duration: "4 Hours",
    description:
      "Affordable tempo traveller from Varanasi to Ara for group travel.",
    highlights: [
      "Smooth Route",
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Ara?",
        answer: "Fare starts from ₹" + 170 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 250,
  },
  {
    id: "vns-pat",
    slug: "varanasi-to-patna-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Patna",
    distance: 260,
    duration: "6 Hours",
    description:
      "Cheapest tempo traveller from Varanasi to Patna for long-distance travel.",
    highlights: [
      "Long Distance Comfort",
      "Safe Travel",
      "Affordable Rates",
      "Group Friendly",
      "Highway Route",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Patna?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "vns-sas",
    slug: "varanasi-to-sasaram-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Sasaram",
    distance: 200,
    duration: "5 Hours",
    description: "Affordable tempo traveller from Varanasi to Sasaram.",
    highlights: [
      "Comfort Travel",
      "Budget Friendly",
      "Safe Ride",
      "Reliable Service",
      "Flexible Timing",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Sasaram?",
        answer: "Fare starts from ₹" + 200 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 350,
  },
  {
    id: "vns-ddu",
    slug: "varanasi-to-deen-dayal-upadhyay-nagar-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "DDU Nagar",
    distance: 18,
    duration: "30 Minutes",
    description: "Very short and cheapest ride from Varanasi to DDU Nagar.",
    highlights: [
      "Ultra Short Trip",
      "Lowest Price",
      "Quick Pickup",
      "Local Drivers",
      "Fast Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to DDU Nagar?",
        answer: "Fare starts from ₹" + 18 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 0,
  },
  {
    id: "vns-rewa",
    slug: "varanasi-to-rewa-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Rewa",
    distance: 260,
    duration: "6 Hours",
    description: "Book cheapest tempo traveller from Varanasi to Rewa.",
    highlights: [
      "Long Route",
      "Comfort Travel",
      "Affordable Pricing",
      "Safe Ride",
      "Group Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Rewa?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "vns-sgr",
    slug: "varanasi-to-singrauli-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Singrauli",
    distance: 300,
    duration: "7 Hours",
    description: "Affordable tempo traveller from Varanasi to Singrauli.",
    highlights: [
      "Long Distance",
      "Comfort Ride",
      "Safe Travel",
      "Reliable Service",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Singrauli?",
        answer: "Fare starts from ₹" + 300 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 500,
  },
  {
    id: "vns-all",
    slug: "varanasi-to-allahabad-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Allahabad",
    distance: 120,
    duration: "3 Hours",
    description:
      "Cheapest tempo traveller from Varanasi to Allahabad (Prayagraj).",
    highlights: [
      "Fast Route",
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Allahabad?",
        answer: "Fare starts from ₹" + 120 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 150,
  },
  {
    id: "vns-gaya",
    slug: "varanasi-to-gaya-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Gaya",
    distance: 260,
    duration: "6 Hours",
    description: "Affordable tempo traveller from Varanasi to Gaya.",
    highlights: [
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "Experienced Drivers",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Gaya?",
        answer: "Fare starts from ₹" + 260 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "vns-deoria",
    slug: "varanasi-to-deoria-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Deoria",
    distance: 230,
    duration: "5 Hours",
    description: "Cheapest tempo traveller from Varanasi to Deoria.",
    highlights: [
      "Long Route",
      "Comfort Travel",
      "Affordable Pricing",
      "Safe Ride",
      "Group Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Deoria?",
        answer: "Fare starts from ₹" + 230 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 400,
  },
  {
    id: "vns-ballia",
    slug: "varanasi-to-ballia-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Ballia",
    distance: 140,
    duration: "3.5 Hours",
    description: "Affordable tempo traveller from Varanasi to Ballia.",
    highlights: [
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "Flexible Timing",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Ballia?",
        answer: "Fare starts from ₹" + 140 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 200,
  },
  {
    id: "vns-basti",
    slug: "varanasi-to-basti-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Basti",
    distance: 240,
    duration: "5.5 Hours",
    description: "Cheapest tempo traveller from Varanasi to Basti.",
    highlights: [
      "Long Distance",
      "Comfort Ride",
      "Safe Travel",
      "Reliable Service",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Basti?",
        answer: "Fare starts from ₹" + 240 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "vns-kushinagar",
    slug: "varanasi-to-kushinagar-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Kushinagar",
    distance: 270,
    duration: "6 Hours",
    description: "Book cheapest tempo traveller from Varanasi to Kushinagar.",
    highlights: [
      "Buddhist Circuit",
      "Comfort Travel",
      "Budget Friendly",
      "Safe Ride",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Kushinagar?",
        answer: "Fare starts from ₹" + 270 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 450,
  },
  {
    id: "vns-sonbhadra",
    slug: "varanasi-to-sonbhadra-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Sonbhadra",
    distance: 180,
    duration: "4.5 Hours",
    description: "Affordable tempo traveller from Varanasi to Sonbhadra.",
    highlights: [
      "Budget Friendly",
      "Comfort Ride",
      "Safe Travel",
      "Flexible Timing",
      "Reliable Service",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Sonbhadra?",
        answer: "Fare starts from ₹" + 180 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 300,
  },
  {
    id: "vns-dhanbad",
    slug: "varanasi-to-dhanbad-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Dhanbad",
    distance: 350,
    duration: "8 Hours",
    description: "Cheapest tempo traveller from Varanasi to Dhanbad.",
    highlights: [
      "Long Route",
      "Comfort Travel",
      "Affordable Pricing",
      "Safe Ride",
      "Group Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Dhanbad?",
        answer: "Fare starts from ₹" + 350 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 600,
  },
  {
    id: "vns-ranchi",
    slug: "varanasi-to-ranchi-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Ranchi",
    distance: 420,
    duration: "9 Hours",
    description: "Affordable tempo traveller from Varanasi to Ranchi.",
    highlights: [
      "Long Distance",
      "Comfort Ride",
      "Safe Travel",
      "Reliable Service",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Ranchi?",
        answer: "Fare starts from ₹" + 420 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 700,
  },
  {
    id: "vns-kanpur",
    slug: "varanasi-to-kanpur-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Kanpur",
    distance: 330,
    duration: "7 Hours",
    description: "Book cheapest tempo traveller from Varanasi to Kanpur.",
    highlights: [
      "Highway Route",
      "Comfort Travel",
      "Affordable Pricing",
      "Safe Ride",
      "Group Friendly",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Kanpur?",
        answer: "Fare starts from ₹" + 330 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 550,
  },
  {
    id: "vns-delhi",
    slug: "varanasi-to-delhi-cheapest-tempo-traveller-fare",
    origin: "Varanasi",
    destination: "Delhi",
    distance: 820,
    duration: "14 Hours",
    description:
      "Long-distance cheapest tempo traveller from Varanasi to Delhi.",
    highlights: [
      "Long Distance",
      "Comfort Ride",
      "Safe Travel",
      "Reliable Service",
      "Experienced Drivers",
    ],
    faqs: [
      {
        question: "What is the fare from Varanasi to Delhi?",
        answer: "Fare starts from ₹" + 820 * VEHICLES[0].perKmRate,
      },
    ],
    tollEstimate: 1500,
  },
];
